services:
  mysql:
    build: ./db
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tcc123  # Senha do root
    volumes:
      - ./resources/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 1

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - LANG=pt_BR.UTF-8  # Idioma em Português do Brasil
      - LANGUAGE=pt_BR:pt  # Ordem de preferência de idioma
      - LC_ALL=pt_BR.UTF-8  # Configurações regionais completas para Português do Brasil
    volumes:
      - ./db/:/schema  # Monta a pasta local no container
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped